name: z1racing
description: A sample game featuring Flame and Forge2D for DartPad
publish_to: "none"
version: 01.01.03+15

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.3
  collection: ^1.18.0
  firebase_analytics: ^10.7.2
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  firebase_crashlytics: ^3.4.8
  flame: ^1.11.0
  flame_audio: ^2.1.4
  flame_forge2d: ^0.16.0+1
  flame_tiled: ^1.18.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  google_mobile_ads: ^4.0.0
  intl: any
  package_info_plus: ^5.0.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  vector_math: ^2.1.4
  vk: ^0.2.1

dev_dependencies:
  flame_lint: ^1.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_alpha.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#000000"
  background_color_ios: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo_alpha.png"
  web:
    generate: true
    image_path: "assets/images/logo_app.png"
    background_color: "#000000"
    theme_color: "#a9d191"
  macos:
    generate: true
    image_path: "assets/images/logo_app.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/avatars/
    - assets/audio/
    - google_fonts/
