name: z1racing
description: A sample game featuring Flame and Forge2D for DartPad
publish_to: "none"
version: 1.0.7+10

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  flame: ^1.11.0
  flame_forge2d: ^0.16.0+1
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  google_fonts: ^6.1.0

  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  firebase_analytics: ^10.7.2
  cloud_firestore: ^4.13.3
  flame_audio: ^2.1.4

  package_info_plus: ^5.0.1
  vk: ^0.2.1

dev_dependencies:
  flame_lint: ^1.1.2
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_alpha.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#a9d191"
  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "assets/images/logo_app.png"
    background_color: "#a9d191"
    theme_color: "#a9d191"
  macos:
    generate: true
    image_path: "assets/images/logo_app.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - google_fonts/
