name: z1racing
description: A sample game featuring Flame and Forge2D for DartPad
publish_to: "none"
version: 1.0.3+6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  flame: ^1.10.0
  flame_forge2d: ^0.15.1
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  google_fonts: ^6.1.0

  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  firebase_analytics: ^10.6.3
  cloud_firestore: ^4.12.2

  package_info_plus: ^4.2.0
  vk: ^0.2.1

dev_dependencies:
  flame_lint: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo_alpha.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#a9d191"
  web:
    generate: true
    image_path: "assets/images/logo_app.png"
    background_color: "#a9d191"
    theme_color: "#a9d191"
  macos:
    generate: true
    image_path: "assets/images/logo_app.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - google_fonts/
