name: z1racing
description: A sample game featuring Flame and Forge2D for DartPad
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  flame: ^1.10.0
  flame_forge2d: ^0.15.1
  flutter:
    sdk: flutter
  url_launcher: ^6.1.11
  google_fonts: ^6.1.0

  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  firebase_analytics: ^10.6.3
  cloud_firestore: ^4.12.2

dev_dependencies:
  flame_lint: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - google_fonts/
