part of 'mock_track.dart';

class MockTrack10 extends MockTrack {
  @override
  Z1Track getTrack() {
    return Z1Track.fromMap({
      'slots': [
        {
          'type': 'rect',
          'length': 50.0,
          'closedSide': 'none',
          'closedAdded': 'none',
        },
        {
          'type': 'rect',
          'length': 50.0,
          'closedSide': 'none',
          'closedAdded': 'none',
          'level': 'bridge',
        },
        {
          'type': 'rect',
          'length': 140.0,
          'closedSide': 'none',
          'closedAdded': 'none',
          'level': 'bridge',
        },
        {
          'type': 'rect',
          'length': 35.0,
          'closedSide': 'none',
          'closedAdded': 'none',
          'level': 'bridge',
        },
        {
          'type': 'rect',
          'length': 30.0,
          'closedSide': 'none',
          'closedAdded': 'none',
        },
        {
          'type': 'rect',
          'length': 20.0,
          'closedSide': 'none',
          'closedAdded': 'none',
        },
        {
          'type': 'curve',
          'angle': 45.0,
          'radius': 90.0,
          'added': true,
          'direction': 'right',
          'closedAdded': 'both',
        },
        {
          'type': 'rect',
          'length': 50.0,
          'closedSide': 'left',
          'closedAdded': 'start',
        },
        {
          'type': 'curve',
          'angle': 90.0,
          'radius': 200.0,
          'added': true,
          'direction': 'left',
          'closedAdded': 'none',
        },
        {
          'type': 'rect',
          'length': 50.0,
          'closedSide': 'left',
          'closedAdded': 'end',
        },
        {
          'type': 'curve',
          'angle': 90.0,
          'radius': 90.0,
          'added': true,
          'direction': 'right',
          'closedAdded': 'start',
        },
        {
          'type': 'curve',
          'angle': 90.0,
          'radius': 90.0,
          'added': true,
          'direction': 'right',
          'closedAdded': 'none',
        },
        {
          'type': 'rect',
          'length': 50.0,
          'closedSide': 'right',
          'closedAdded': 'end',
          'level': 'bridge',
        },
        {
          'type': 'curve',
          'angle': 90.0,
          'radius': 90.0,
          'added': false,
          'direction': 'right',
          'closedAdded': 'none',
          'level': 'bridge',
        },
        {
          'type': 'curve',
          'angle': 90.0,
          'radius': 90.0,
          'added': false,
          'direction': 'right',
          'closedAdded': 'none',
          'level': 'bridge',
        },
        {
          'type': 'curve',
          'angle': 90.0,
          'radius': 90.0,
          'added': false,
          'direction': 'left',
          'closedAdded': 'none',
          'level': 'bridge',
        },
        {
          'type': 'rect',
          'length': 50.0,
          'closedSide': 'none',
          'closedAdded': 'none',
          'level': 'bridge',
        },
        {
          'type': 'curve',
          'angle': 45.0,
          'radius': 90.0,
          'added': false,
          'direction': 'left',
          'closedAdded': 'none',
          'level': 'bridge',
        },
        {
          'type': 'curve',
          'angle': 90.0,
          'radius': 90.0,
          'added': false,
          'direction': 'right',
          'closedAdded': 'none',
          'level': 'bridge',
        },
        {
          'type': 'curve',
          'angle': 90.0,
          'radius': 90.0,
          'added': false,
          'direction': 'right',
          'closedAdded': 'none',
          'level': 'bridge',
        },
        {
          'type': 'rect',
          'length': 50.0,
          'closedSide': 'none',
          'closedAdded': 'none',
          'level': 'bridge',
        },
        {
          'type': 'rect',
          'length': 50.0,
          'closedSide': 'none',
          'closedAdded': 'none',
        },
        {
          'type': 'curve',
          'angle': 90.0,
          'radius': 90.0,
          'added': true,
          'direction': 'right',
          'closedAdded': 'start',
        },
        {
          'type': 'curve',
          'angle': 45.0,
          'radius': 90.0,
          'added': true,
          'direction': 'right',
          'closedAdded': 'end',
        },
        {
          'type': 'rect',
          'length': 150.0,
          'closedSide': 'none',
          'closedAdded': 'none',
        },
        {
          'type': 'curve',
          'angle': 45.0,
          'radius': 90.0,
          'added': true,
          'direction': 'right',
          'closedAdded': 'start',
        },
        {
          'type': 'rect',
          'length': 50.0,
          'closedSide': 'right',
          'closedAdded': 'none',
        },
        {
          'type': 'curve',
          'angle': 45.0,
          'radius': 90.0,
          'added': true,
          'direction': 'right',
          'closedAdded': 'none',
        },
        {
          'type': 'rect',
          'length': 50.0,
          'closedSide': 'right',
          'closedAdded': 'end',
        },
        {
          'type': 'rect',
          'length': 50.0,
          'closedSide': 'none',
          'closedAdded': 'none',
        },
        {
          'type': 'rect',
          'length': 200.0,
          'closedSide': 'none',
          'closedAdded': 'none',
        },
        {
          'type': 'curve',
          'angle': 90.0,
          'radius': 90.0,
          'added': true,
          'direction': 'left',
          'closedAdded': 'start',
        },
        {
          'type': 'curve',
          'angle': 90.0,
          'radius': 90.0,
          'added': true,
          'direction': 'left',
          'closedAdded': 'end',
        },
        {
          'type': 'curve',
          'angle': 90.0,
          'radius': 170.0,
          'added': true,
          'direction': 'right',
          'closedAdded': 'both',
        },
        {
          'type': 'curve',
          'angle': 90.0,
          'radius': 90.0,
          'added': true,
          'direction': 'left',
          'closedAdded': 'start',
        },
        {
          'type': 'rect',
          'length': 50.0,
          'closedSide': 'left',
          'closedAdded': 'end',
        },
        {
          'type': 'rect',
          'length': 150.0,
          'closedSide': 'none',
          'closedAdded': 'none',
        },
        {
          'type': 'curve',
          'angle': 90.0,
          'radius': 90.0,
          'added': true,
          'direction': 'left',
          'closedAdded': 'start',
        },
        {
          'type': 'curve',
          'angle': 45.0,
          'radius': 90.0,
          'added': true,
          'direction': 'left',
          'closedAdded': 'none',
        },
        {
          'type': 'rect',
          'length': 40.0,
          'closedSide': 'left',
          'closedAdded': 'end',
        },
        {
          'type': 'rect',
          'length': 50.0,
          'closedSide': 'none',
          'closedAdded': 'none',
          'level': 'bridge',
        },
        {
          'type': 'rect',
          'length': 300.0,
          'closedSide': 'none',
          'closedAdded': 'none',
          'level': 'bridge',
        },
        {
          'type': 'curve',
          'angle': 90.0,
          'radius': 90.0,
          'added': false,
          'direction': 'left',
          'closedAdded': 'none',
          'level': 'bridge',
        },
        {
          'type': 'rect',
          'length': 300.0,
          'closedSide': 'none',
          'closedAdded': 'none',
          'level': 'bridge',
        },
        {
          'type': 'rect',
          'length': 40.0,
          'closedSide': 'none',
          'closedAdded': 'none',
          'level': 'bridge',
        },
        {
          'type': 'rect',
          'length': 40.0,
          'closedSide': 'none',
          'closedAdded': 'none',
          'sensor': 'finish',
        },
        {
          'type': 'curve',
          'angle': 90.0,
          'radius': 90.0,
          'added': true,
          'direction': 'left',
          'closedAdded': 'start',
        },
        {
          'type': 'rect',
          'length': 32.5,
          'closedSide': 'left',
          'closedAdded': 'none',
        },
        {
          'type': 'curve',
          'angle': 90.0,
          'radius': 90.0,
          'added': true,
          'direction': 'left',
          'closedAdded': 'end',
        },
        {
          'type': 'rect',
          'length': 25.0,
          'closedSide': 'none',
          'closedAdded': 'none',
        },
      ],
      'objects': [],
      'trackId': 'Mock2TrackId_b9',
      'name': 'The Mock 9 Track',
      'numLaps': 3,
      'version': 1,
      'vorder': 10,
      'enabled': true,
      'carInitAngle': 3.055,
    });
  }
}
