# This is a basic workflow to help you get started with Actions
name: Deploy Google Play Console

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
    paths-ignore:
      - "**/README.md"

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "3.13.9"
      KEY_JKS: ${{ secrets.KEY_JKS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      GOOGLE_SERVICE_ANDROID: ${{ secrets.GOOGLE_SERVICE_ANDROID }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.9"
      - run: mkdir keys; echo $KEY_JKS | base64 -d > keys/z1racing.keystore
      - run: echo $GOOGLE_SERVICE_ANDROID | base64 -d > android/app/google-services.json
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build appbundle --release
      - uses: actions/upload-artifact@v1
        with:
          name: release-appbundle
          path: build/app/outputs/bundle/release/app-release.aab
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.zwymobile.z1racing
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
          status: inProgress
          inAppUpdatePriority: 2
          userFraction: 0.33
          whatsNewDirectory: distribution/whatsnew
          mappingFile: build/app/outputs/mapping/release/mapping.txt
          debugSymbols: build/app/intermediates/merged_native_libs/release/out/lib
